### PR TITLE
Update to Lightbits v3.9.1

### PR DESCRIPTION
**Pull request by majst01**

### CODE REVIEW

**Comment by robertvolkmann** [comment]
Where I can find the origin source of `durosapiv2.proto`?

**Comment by majst01** [comment]
> Where I can find the origin source of `durosapiv2.proto`?

Sadly there is no public repo with these proto files, i always ask lightbits to send me them.

**Comment by robertvolkmann** [comment]
Could you send me them.

**Comment by majst01** [comment]
> Could you send me them.

They are checked in here: https://github.com/metal-stack/duros-go/tree/lightos-3.9.1/proto/lightbits/api/duros/v2

**Review by robertvolkmann — APPROVED** [review]

**Pull request merged**
